name: Android APK (Release)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PATH: android/app/keystore.jks
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Prepare keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > "$ANDROID_KEYSTORE_PATH" || true

      - name: Validate secrets/keystore
        run: |
          test -n "${{ env.ANDROID_KEYSTORE_PASSWORD }}" || (echo "MISSING ANDROID_KEYSTORE_PASSWORD" && exit 1)
          test -n "${{ env.ANDROID_KEY_ALIAS }}" || (echo "MISSING ANDROID_KEY_ALIAS" && exit 1)
          test -n "${{ env.ANDROID_KEY_PASSWORD }}" || (echo "MISSING ANDROID_KEY_PASSWORD" && exit 1)
          if [ ! -s "$ANDROID_KEYSTORE_PATH" ]; then
            echo "Keystore not found at $ANDROID_KEYSTORE_PATH. Check ANDROID_KEYSTORE_BASE64.";
            exit 1
          fi
          ls -l "$ANDROID_KEYSTORE_PATH"

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
