name: Build AAB (fresh key)
on:
  workflow_dispatch:
    inputs:
      STORE_PASSWORD: { description: "Keystore password", required: true }
      KEY_PASSWORD:   { description: "Key password (can be same)", required: true }
      KEY_ALIAS:      { description: "Alias", required: true, default: upload }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.22.0', channel: stable }

      - name: Write local.properties
        run: |
          mkdir -p android
          FLUTTER_SDK=$(dirname "$(dirname "$(which flutter)")")
          echo "flutter.sdk=$FLUTTER_SDK" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties

      - name: Precache Flutter engine
        run: flutter precache --android --force

      - name: Generate upload keystore (fresh)
        run: |
          mkdir -p android/app
          keytool -genkeypair -v -storetype JKS \
            -keystore android/app/upload-keystore.jks \
            -alias "${{ github.event.inputs.KEY_ALIAS }}" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "${{ github.event.inputs.STORE_PASSWORD }}" \
            -keypass   "${{ github.event.inputs.KEY_PASSWORD }}" \
            -dname "CN=Upload, OU=CI, O=App, L=, S=, C=US"
          echo "ANDROID_KEYSTORE_PATH=$GITHUB_WORKSPACE/android/app/upload-keystore.jks" >> $GITHUB_ENV
          base64 -w 0 android/app/upload-keystore.jks > upload-keystore.jks.base64 || base64 android/app/upload-keystore.jks | tr -d "\n" > upload-keystore.jks.base64

      - name: Keystore sanity
        env:
          STORE_PASSWORD: ${{ github.event.inputs.STORE_PASSWORD }}
          KEY_PASSWORD:   ${{ github.event.inputs.KEY_PASSWORD }}
          KEY_ALIAS:      ${{ github.event.inputs.KEY_ALIAS }}
        run: |
          set -e
          keytool -list -keystore android/app/upload-keystore.jks -storepass "$STORE_PASSWORD"
          keytool -exportcert -rfc -alias "$KEY_ALIAS" \
            -keystore android/app/upload-keystore.jks \
            -storepass "$STORE_PASSWORD" -keypass "$KEY_PASSWORD" \
            -file /tmp/dummy.pem

      - name: flutter pub get
        run: flutter pub get

      - name: Build signed AAB (unique versionCode)
        env:
          KEY_ALIAS:      ${{ github.event.inputs.KEY_ALIAS }}
          KEY_PASSWORD:   ${{ github.event.inputs.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ github.event.inputs.STORE_PASSWORD }}
        run: flutter build appbundle --release --build-number $GITHUB_RUN_NUMBER

      - name: Upload artifact (AAB + keystore base64)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab-and-key
          path: |
            build/app/outputs/bundle/release/app-release.aab
            upload-keystore.jks.base64 