name: Build Flutter AAB

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: stable

      - name: Restore keystore from secrets
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
          echo "ANDROID_KEYSTORE_PATH=$GITHUB_WORKSPACE/android/app/upload-keystore.jks" >> $GITHUB_ENV
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Install deps
        run: flutter pub get

      # Optional: bump versionCode so Play accepts each build
      - name: Bump versionCode in build.gradle
        run: |
          FILE=android/app/build.gradle
          CODE=$(grep -oP 'versionCode \K[0-9]+' $FILE)
          NEW=$((CODE+1))
          sed -i "s/versionCode $CODE/versionCode $NEW/" $FILE
          git config user.email "ci@github" && git config user.name "ci"
          git add $FILE && git commit -m "CI: bump versionCode to $NEW" || true

      - name: Build **AAB** (not APK)
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: flutter build appbundle --release

      - name: Upload artifact (AAB)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      # ---- OPTIONAL: auto-upload to Play Internal track ----
      - name: Upload to Play Internal
        if: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON != '' }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.beguileai.app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
