name: iOS Build (Flutter)

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: "Flutter version"
        required: false
        default: "3.24.1"
      build_flavor:
        description: "Flutter flavor (optional)"
        required: false
        default: ""
      build_number:
        description: "iOS build number"
        required: false
        default: "1"

jobs:
  build-ios:
    runs-on: macos-14
    timeout-minutes: 60

    env:
      FLUTTER_VERSION: ${{ inputs.flutter_version }}
      BUILD_NUMBER: ${{ github.run_number }}
      FLAVOR: ${{ inputs.build_flavor }}
      ENABLE_CODE_SIGN: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod repo update
          pod install

      - name: Build iOS (unsigned)
        run: |
          if [ -n "${{ env.FLAVOR }}" ]; then
            flutter build ipa --no-codesign --flavor "${{ env.FLAVOR }}" --build-number "${{ env.BUILD_NUMBER }}"
          else
            flutter build ipa --no-codesign --build-number "${{ env.BUILD_NUMBER }}"
          fi

      - name: Upload Runner.app
        uses: actions/upload-artifact@v4
        with:
          name: ios-Runner-app
          path: build/ios/iphoneos/Runner.app
          if-no-files-found: warn

      - name: Upload xcarchive
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcarchive
          path: build/ios/archive/*.xcarchive
          if-no-files-found: warn
