name: Secret Probe
on: workflow_dispatch

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Check signing secrets presence
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEY_ALIAS:               ${{ secrets.KEY_ALIAS }}
          STORE_PASSWORD:          ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD:            ${{ secrets.KEY_PASSWORD }}
        run: |
          set -e
          echo "ANDROID_KEYSTORE_BASE64: ${#ANDROID_KEYSTORE_BASE64} bytes"
          test -n "$KEY_ALIAS"      && echo "KEY_ALIAS: present"      || (echo "KEY_ALIAS: MISSING"; exit 1)
          test -n "$STORE_PASSWORD" && echo "STORE_PASSWORD: present" || (echo "STORE_PASSWORD: MISSING"; exit 1)
          test -n "$KEY_PASSWORD"   && echo "KEY_PASSWORD: present"   || (echo "KEY_PASSWORD: MISSING"; exit 1) 